Blog.Net/src/Blog.Web/ViewModels/PostagemViewModel.cs
using Blog.Business.Models;
using System.ComponentModel.DataAnnotations;

namespace Blog.Web.ViewModels
{
    public class PostagemViewModel
    {
        [Key]
        public Guid Id { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [StringLength(200, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres", MinimumLength = 2)]
        public string? Titulo { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [StringLength(2000, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres", MinimumLength = 2)]
        public string? Conteudo { get; set; }

        [Display(Name = "Data Postagem")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm:ss}")]
        public DateTime? DataCriacao { get; set; }

        [Display(Name = "Data Atualização")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm:ss}")]
        public DateTime? DataAtualizacao { get; set; }

        public Guid IdAutor { get; set; }
        public Autor? Autor { get; set; }

        public List<ComentarioViewModel>? Comentarios { get; set; }
    }
}

Blog.Net/src/Blog.Web/Components/SummaryViewComponent.cs
using Blog.Business.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Web.Components
{
    public class SummaryViewComponent : ViewComponent
    {
        private readonly INotificador _notificador;

        public SummaryViewComponent(INotificador notificador)
        {
            _notificador = notificador;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notificacoes = await Task.FromResult(_notificador.ObterNotificacoes());
            notificacoes.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c.Mensagem));

            return View();
        }
    }
}

Blog.Net/src/Blog.Web/Controllers/ComentariosController.cs
using AutoMapper;
using Blog.Business.Interfaces;
using Blog.Business.Models;
using Blog.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Web.Controllers
{

    [Authorize]
    public class ComentariosController : BaseController
    {
        private readonly IMapper _mapper;

        private readonly IComentarioRepository _comentarioRepository;
        private readonly IComentarioService _comentarioService;

        private readonly IAutorRepository _autorRepository;
        private readonly IAutorService _autorService;


        public ComentariosController(IMapper mapper,
                                     IComentarioRepository repository,
                                     IComentarioService service,
                                     IAutorRepository autorRepository,
                                     IAutorService autorService,
                                     INotificador notificador,
                                     IAppIdentityUser user) : base(notificador, user)
        {
            _mapper = mapper;

            _comentarioRepository = repository;
            _comentarioService = service;

            _autorRepository = autorRepository;
            _autorService = autorService;
        }

        [AllowAnonymous]
        [HttpGet]
        [Route("lista-de-comentarios")]
        public async Task<IActionResult> Index()
        {
            ViewBag.IdUser = UserId;
            ViewBag.Admin = UserAdmin;

            return View(_mapper.Map<IEnumerable<ComentarioViewModel>>(await _comentarioRepository.ObterTodos()));

        }

        [AllowAnonymous]
        [HttpGet]
        [Route("dados-do-comentario/{id:guid}")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ViewBag.IdUser = UserId;
            ViewBag.Admin = UserAdmin;


            ComentarioViewModel? comentario = await ObterComentario(id);

            if (comentario == null)
            {
                return NotFound();
            }

            ViewData["Title"] = "Excluir Comentário";
            return View(comentario);
        }


        [HttpGet]
        [Route("novo-comentario/{id:guid}")]
        public async Task<IActionResult> Create(Guid id)
        {
            await CriarAutorSeNaoExistir();

            ViewBag.idPostagem = id.ToString();

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("novo-comentario/{id:guid}")]
        public async Task<IActionResult> Create([Bind("Conteudo,IdPostagem")] ComentarioViewModel comentario)
        {
            ModelState.Remove("DataPostagem");
            if (ModelState.IsValid)
            {
                await CriarAutorSeNaoExistir();

                comentario.Id = Guid.NewGuid();
                comentario.Conteudo = comentario.Conteudo;
                comentario.IdPostagem = comentario.IdPostagem;
                comentario.DataPostagem = DateTime.Now;
                comentario.IdAutor = UserId;
                comentario.NomeAutor = UserName;

                await _comentarioService.Adicionar(_mapper.Map<Comentario>(comentario));

                if (!OperacaoValida())
                {
                    ViewBag.idPostagem = comentario.Id.ToString();
                    return View(comentario);
                }

                return RedirectToAction("Details", "Postagem", new { id = comentario.IdPostagem });
            }
            
            return View(comentario);
        }


        [HttpGet]
        [Route("editar-comentario/{id:guid}")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null) return NotFound();

            ComentarioViewModel? comentario = await ObterComentario(id);
            
            if (comentario == null) return NotFound();

            if (!UsuarioPodeModificar(comentario))  return Unauthorized();

            return View(comentario);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("editar-comentario/{id:guid}")]
        public async Task<IActionResult> Edit(Guid id, [Bind("Conteudo,DataPostagem,IdAutor,IdPostagem,Id")] ComentarioViewModel comentario)
        {
            if (id != comentario.Id) return NotFound();

            ModelState.Remove("DataPostagem");

            if (ModelState.IsValid)
            {
                ComentarioViewModel? _comentarioDB = await ObterComentario(id);

                if (!UsuarioPodeModificar(comentario))  return Unauthorized();

                if (_comentarioDB == null)  return NotFound();

                _comentarioDB.Conteudo = comentario.Conteudo;

                await _comentarioService.Atualizar(_mapper.Map<Comentario>(_comentarioDB));

                if (!OperacaoValida())
                {
                    ViewData["IdPostagem"] = id.ToString();
                    return View(comentario);
                }


                return RedirectToAction("Details", "Postagem", new { id = comentario.IdPostagem });
            }
            ViewData["IdPostagem"] = id.ToString() ;
            return View(comentario);
        }


        [HttpGet]
        [Route("deletar-comentario/{id:guid}")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null) return NotFound();

            ComentarioViewModel? comentario = await ObterComentario(id);

            if (comentario == null)  return NotFound();

            if (!UsuarioPodeModificar(comentario)) return Unauthorized();

            return View(comentario);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Route("deletar-comentario/{id:guid}")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            ComentarioViewModel? comentario = await ObterComentario(id);

            if (comentario == null) return NotFound();

            if (comentario != null)
            {
                if (!UsuarioPodeModificar(comentario))  return Unauthorized();

                await _comentarioService.Remover(comentario.Id);

                if (!OperacaoValida()) return View(comentario);

                return RedirectToAction("Details", "Postagem", new { id = comentario.IdPostagem });
            }

            return RedirectToAction("Index", "Postagem");
        }

        private bool ExiteComentario(Guid id)
        {
            return _comentarioRepository.ObterPorId(id) != null ? true : false;
        }

        private async Task<ComentarioViewModel?> ObterComentario(Guid? id)
        {
            if (id == null)
                return null;

            ComentarioViewModel comentario = _mapper.Map<ComentarioViewModel>(await _comentarioRepository.ObterComentario(id ?? Guid.Empty));
            return comentario;
        }


        private bool UsuarioPodeModificar(ComentarioViewModel comentario)
        {
            return UserAdmin || UserId == comentario.IdAutor;
        }

        private async Task CriarAutorSeNaoExistir()
        {
            IEnumerable<Autor> _autor = await _autorRepository.Buscar(p => p.Id == UserId);

            if (_autor == null || !_autor.Any())
            {
                var _insAutor = new Autor
                {
                    Email = UserName,
                    Nome = UserName,
                    Id = UserId,
                    Biografia = ""
                };

                await _autorService.Adicionar(_insAutor);
            }
        }
    }
}

Blog.Net/src/Blog.Web/Controllers/PostagemController.cs
using AutoMapper;
using Blog.Business.Interfaces;
using Blog.Business.Models;
using Blog.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Web.Controllers
{
    [Authorize]
    public class PostagemController : BaseController
    {
        private readonly IMapper _mapper;

        private readonly IPostagemRepository _postagemRepository;
        private readonly IPostagemService _postagemService;

        private readonly IAutorRepository _autorRepository;
        private readonly IAutorService _autorService;


        public PostagemController(IMapper mapper,
                                  IPostagemRepository repository,
                                  IPostagemService service,
                                  IAutorRepository autorRepository,
                                  IAutorService autorService,
                                  INotificador notificador,
                                  IAppIdentityUser user) : base(notificador, user)
        {
            _mapper = mapper;

            _postagemRepository = repository;
            _postagemService = service;

            _autorRepository = autorRepository;
            _autorService = autorService;
        }


        [AllowAnonymous]
        [HttpGet]
        [Route("lista-de-postagem")]
        public async Task<IActionResult> Index()
        {
            
            ViewBag.IdUser = UserId;
            ViewBag.Admin = UserAdmin;

            return View(_mapper.Map<List<PostagemViewModel>>(await _postagemRepository.ObterTodasPostagem()));

        }

        [AllowAnonymous]
        [HttpGet]
        [Route("dados-da-postagem/{id:guid}")]
        public async Task<IActionResult> Details(Guid id)
        {
            ViewBag.IdUser = UserId;
            ViewBag.Admin = UserAdmin;

            PostagemViewModel postagemViewModel = await ObterPostagem(id);

            if (postagemViewModel == null)
            {
                return NotFound();
            }

            return View(postagemViewModel);
        }


        [HttpGet]
        [Route("nova-postagem")]
        public async Task<IActionResult> Create()
        {
            IEnumerable<Autor> _autor = await _autorRepository.Buscar(p => p.Id == UserId);

            await CriarAutorSeNaoExistir();

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("nova-postagem")]
        public async Task<IActionResult> Create([Bind("Titulo,Conteudo")] PostagemViewModel postagemViewModel)
        {
            if (ModelState.IsValid)
            {
                await CriarAutorSeNaoExistir();

                postagemViewModel.Id = Guid.NewGuid();
                postagemViewModel.DataCriacao = DateTime.Now;
                postagemViewModel.IdAutor = UserId;

                await _postagemService.Adicionar(_mapper.Map<Postagem>(postagemViewModel));

                return RedirectToAction("Index");

            }
            return View(postagemViewModel);
        }


        [HttpGet, ActionName("Edit")]
        [Route("editar-postagem/{id:guid}")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)  return NotFound();

            PostagemViewModel? postagem = await ObterPostagem(id);

            if(postagem == null) return NotFound();

            if (!UsuarioPodeModificar(postagem)) return Unauthorized();

            if (postagem == null) return NotFound();
            
            return View(postagem);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("editar-postagem/{id:guid}")]
        public async Task<IActionResult> Edit(Guid id, [Bind("Titulo,Conteudo,DataCriacao,IdAutor,Id")] PostagemViewModel postagem)
        {
            if (id != postagem.Id)  return NotFound();

            if (!UsuarioPodeModificar(postagem)) return Unauthorized();

            if (ModelState.IsValid)
            {
                postagem.DataAtualizacao = DateTime.Now;
                await _postagemRepository.Atualizar(_mapper.Map<Postagem>(postagem));

                return RedirectToAction(nameof(Index));
            }

            return View(postagem);
        }


        [HttpGet, ActionName("Delete")]
        [Route("excluir-postagem/{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            PostagemViewModel? postagem = await ObterPostagem(id);

            if (postagem == null) return NotFound();

            if (!UsuarioPodeModificar(postagem)) return Unauthorized();

            return View(postagem); 
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Route("excluir-postagem/{id:guid}")]
        public async Task<IActionResult> DeleteConfirmado(Guid id)
        {
            PostagemViewModel? postagem = await ObterPostagem(id);

            if (postagem == null) return NotFound();

            if (!UsuarioPodeModificar(postagem)) return Unauthorized();

            await _postagemService.Remover(id);

            return RedirectToAction("Index");
        }



        private bool PostagemExists(Guid id)
        {
            return _postagemRepository.ObterPostagem(id) != null;
        }


        private async Task<PostagemViewModel?> ObterPostagem(Guid? id)
        {
            if (id == null)
                return null;

            var postagem = _mapper.Map<PostagemViewModel>(await _postagemRepository.ObterPostagem(Guid.Parse(id.ToString())));
            return postagem;
        }

        private bool UsuarioPodeModificar(PostagemViewModel comentario)
        {
            return UserAdmin || UserId == comentario.IdAutor;
        }

        private async Task CriarAutorSeNaoExistir()
        {
            IEnumerable<Autor> _autor = await _autorRepository.Buscar(p => p.Id == UserId);

            if (_autor == null || !_autor.Any())
            {
                var _insAutor = new Autor
                {
                    Email = UserName,
                    Nome = UserName,
                    Id = UserId,
                    Biografia = ""
                };


                await _autorService.Adicionar(_insAutor);
            }
        }

    }
}

Blog.Net/src/Blog.Web/Views/Postagem/Create.cshtml
@using Blog.Web.ViewModels
@model PostagemViewModel

@{
     ViewData["Title"] = "Criar Postagem";
 }

@await Component.InvokeAsync("Summary")

<h4>Postagem</h4>
<hr />

<div class="row">
    <div class="col-md-8">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Conteudo" class="control-label"></label>
                <textarea asp-for="Conteudo" class="form-control" rows="5"></textarea>
                <span asp-validation-for="Conteudo" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-danger">Cancelar</a>
            </div>
        </form>
    </div>
</div>

@* <div>
    <a asp-action="Index">Voltar</a>
</div> *@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Blog.Net/src/Blog.Web/Views/Postagem/Delete.cshtml
@using Blog.Web.ViewModels
@model PostagemViewModel

@{
    ViewData["Title"] = "Excluir";
}

@await Component.InvokeAsync("Summary")

<div class="container mt-4">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class="text">Excluir Postagem</h1>
            <h3 class="text">Tem certeza de que deseja excluir esta postagem?</h3>
            <div class="card border-danger mb-3">
                <div class="card-header bg-danger text-white">
                    <h4>Detalhes da Postagem</h4>
                </div>
                <div class="card-body">
                    <dl class="row">
                        <dt class="col-sm-3">Título</dt>
                        <dd class="col-sm-9">@Html.DisplayFor(model => model.Titulo)</dd>

                        <dt class="col-sm-3">Conteúdo</dt>
                        <dd class="col-sm-9">@Html.DisplayFor(model => model.Conteudo)</dd>

                        <dt class="col-sm-3">Data de Criação</dt>
                        <dd class="col-sm-9">@Html.DisplayFor(model => model.DataCriacao)</dd>
                    </dl>
                </div>
            </div>

            <form asp-action="Delete">
                <input type="hidden" asp-for=@Model.Id />
                <div class="form-group">
                    <a asp-action="Index" class="btn btn-primary">Cancelar</a>
                    <button type="submit" class="btn btn-danger">Excluir</button>
                </div>
            </form>
        </div>
    </div>
</div>

Blog.Net/src/Blog.Web/Views/Postagem/Details.cshtml
@using Blog.Web.ViewModels
@model PostagemViewModel

@{
    ViewBag.Title = Model.Titulo;
    var userId = @ViewBag.IdUser ?? Guid.Empty;
    var isAdmin = @ViewBag.Admin ?? false;

    var idPostagem = Model.Id;
}


<div class="container post-details">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <article class="post">
                <header class="post-header">
                    <h1 class="post-title">@Model.Titulo</h1>
                    <p class="post-meta">
                        Publicado por <strong>@Model.Autor?.Nome</strong> em @Model.DataCriacao?.ToString("dd/MM/yyyy")
                    </p>
                </header>

                <div class="post-content">
                    @Html.Raw(Model.Conteudo?.Replace("\r\n", "<br />").Replace("\n", "<br />").Replace("\r", "<br />"))
                </div>
                <section class="comments-section">
                    <h3>Comentários</h3>
                    @if (Model.Comentarios != null && Model.Comentarios.Any())
                    {
                        <ul class="comments-list">
                            @foreach (var comentario in Model.Comentarios)
                            {
                                <li>
                                    <p>@comentario.Conteudo</p>
                                    <p class="comment-meta">
                                        <small>Por <strong>@comentario.NomeAutor</strong> em @comentario.DataPostagem?.ToString("dd/MM/yyyy")</small>
                                    </p>
                                    @if (userId == comentario?.IdAutor || isAdmin)
                                    {
                                        <a href="@Url.Action("Edit", "Comentarios", new { id = comentario.Id })" class="btn btn-primary btn-sm">Editar</a>
                                        <a href="@Url.Action("Delete", "Comentarios", new { id = comentario.Id })" class="btn btn-danger btn-sm">Excluir</a>
                                    }
                                    else
                                    {
                                        <button class="btn btn-secondary btn-sm" disabled>Editar</button>
                                        <button class="btn btn-secondary btn-sm" disabled>Excluir</button>
                                    }
                                </li>
                            }
                        </ul>
                    }
                    else
                    {
                        <p>Nenhum comentário ainda.</p>
                    }
                </section>
                <div style="text-align: center;margin-bottom: 20px;">
                    
                    @if (idPostagem != Guid.Empty)
                    {
                        @if (Model.Id != Guid.Empty)
                        {
                            <a href="@Url.Action("Create", "Comentarios", new { id = idPostagem })" class="btn btn-primary btn-lg"> + Novo Comentário</a>
                        }
                        else
                        {
                            <p>Id da postagem não está disponível.</p>
                        }
                    }
                    else
                    {
                        <button class="btn btn-secondary btn-lg" disabled>  + Novo Comentário</button>
                    }
                </div>
                <div>
                    <a asp-action="Index">Voltar</a>
                </div>
            </article>
        </div>

    </div>
</div>

Blog.Net/src/Blog.Web/Views/Postagem/Detalhes.cshtml
@using Blog.Business.Models
@model Postagem

@{
    ViewBag.Title = Model.Titulo;
    var userId = @ViewBag.IdUser ?? Guid.Empty;
    var isAdmin = @ViewBag.Admin ?? false;
}


<div class="container post-details">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <article class="post">
                <header class="post-header">
                    <h1 class="post-title">@Model.Titulo</h1>
                    <p class="post-meta">
                        Publicado por <strong>@Model.Autor?.Nome</strong> em @Model.DataCriacao?.ToString("dd/MM/yyyy")
                    </p>
                </header>

                <div class="post-content">
                    @Html.Raw(Model.Conteudo?.Replace("\r\n", "<br />").Replace("\n", "<br />").Replace("\r", "<br />"))
                </div>
                <section class="comments-section">
                    <h3>Comentários</h3>
                    @if (Model.Comentarios != null && Model.Comentarios.Any())
                    {
                        <ul class="comments-list">
                            @foreach (var comentario in Model.Comentarios)
                            {
                                <li>
                                    <p>@comentario.Conteudo</p>
                                    <p class="comment-meta">
                                        <small>Por <strong>@comentario.NomeAutor</strong> em @comentario.DataPostagem?.ToString("dd/MM/yyyy")</small>
                                    </p>
                                    @if (userId == comentario?.IdAutor || isAdmin)
                                    {
                                        <a href="@Url.Action("Editar", "Comentario", new { id = comentario.Id })" class="btn btn-primary btn-sm">Editar</a>
                                        <a href="@Url.Action("Delete", "Comentario", new { id = comentario.Id })" class="btn btn-danger btn-sm">Excluir</a>
                                    }
                                    else
                                    {
                                        <button class="btn btn-secondary btn-sm" disabled>Editar</button>
                                        <button class="btn btn-secondary btn-sm" disabled>Excluir</button>
                                    }
                                </li>
                            }
                        </ul>
                    }
                    else
                    {
                        <p>Nenhum comentário ainda.</p>
                    }
                </section>
                <div style="text-align: center;margin-bottom: 20px;">
                            @if (userId != Guid.Empty)
                    {
                        <a href="@Url.Action("Create", "Postagem", new { area = "" })" class="btn btn-primary btn-lg"> + Novo Comentário</a>
                    }
                    else
                    {
                        <button class="btn btn-secondary btn-lg" disabled>  + Novo Comentário</button>
                    }
                </div>
                <div>
                    <a asp-action="Index">Voltar</a>
                </div>
            </article>
        </div>

    </div>
</div>

Blog.Net/src/Blog.Web/Views/Postagem/Edit.cshtml
@using Blog.Web.ViewModels
@model PostagemViewModel

@{
    ViewData["Title"] = "Editar Postagem";
}

@await Component.InvokeAsync("Summary")

<h4>Postagem</h4>
<hr />

<div class="row">
    <div class="col-md-8">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="IdAutor" class="control-label"></label>
                <input asp-for="IdAutor" class="form-control" readonly />
                <span asp-validation-for="IdAutor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataCriacao" class="control-label"></label>
                <input asp-for="DataCriacao" class="form-control" readonly />
                <span asp-validation-for="DataCriacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Conteudo" class="control-label"></label>
                <textarea asp-for="Conteudo" class="form-control" rows="10"></textarea>
                <span asp-validation-for="Conteudo" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-danger">Cancelar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Blog.Net/src/Blog.Web/Views/Postagem/Index.cshtml
@await Component.InvokeAsync("Postagem")