Blog.Net/src/Blog.Web/Controllers/PostagemController.cs
using AutoMapper;
using Blog.Business.Interfaces;
using Blog.Business.Models;
using Blog.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Web.Controllers
{
    [Authorize]
    public class PostagemController : BaseController
    {
        private readonly IMapper _mapper;

        private readonly IPostagemRepository _postagemRepository;
        private readonly IPostagemService _postagemService;

        private readonly IAutorRepository _autorRepository;
        private readonly IAutorService _autorService;


        public PostagemController(IMapper mapper,
                                  IPostagemRepository repository,
                                  IPostagemService service,
                                  IAutorRepository autorRepository,
                                  IAutorService autorService,
                                  INotificador notificador,
                                  IAppIdentityUser user) : base(notificador, user)
        {
            _mapper = mapper;

            _postagemRepository = repository;
            _postagemService = service;

            _autorRepository = autorRepository;
            _autorService = autorService;
        }


        [AllowAnonymous]
        [HttpGet]
        [Route("lista-de-postagem")]
        public async Task<IActionResult> Index()
        {
            
            ViewBag.IdUser = UserId;
            ViewBag.Admin = UserAdmin;

            return View(_mapper.Map<List<PostagemViewModel>>(await _postagemRepository.ObterTodasPostagem()));

        }

        [AllowAnonymous]
        [HttpGet]
        [Route("dados-da-postagem/{id:guid}")]
        public async Task<IActionResult> Details(Guid id)
        {
            ViewBag.IdUser = UserId;
            ViewBag.Admin = UserAdmin;

            PostagemViewModel postagemViewModel = await ObterPostagem(id);

            if (postagemViewModel == null)
            {
                return NotFound();
            }

            return View(postagemViewModel);
        }


        [HttpGet]
        [Route("nova-postagem")]
        public async Task<IActionResult> Create()
        {
            IEnumerable<Autor> _autor = await _autorRepository.Buscar(p => p.Id == UserId);

            await CriarAutorSeNaoExistir();

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("nova-postagem")]
        public async Task<IActionResult> Create([Bind("Titulo,Conteudo")] PostagemViewModel postagemViewModel)
        {
            if (ModelState.IsValid)
            {
                await CriarAutorSeNaoExistir();

                postagemViewModel.Id = Guid.NewGuid();
                postagemViewModel.DataCriacao = DateTime.Now;
                postagemViewModel.IdAutor = UserId;

                await _postagemService.Adicionar(_mapper.Map<Postagem>(postagemViewModel));

                return RedirectToAction("Index");

            }
            return View(postagemViewModel);
        }


        [HttpGet, ActionName("Edit")]
        [Route("editar-postagem/{id:guid}")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)  return NotFound();

            PostagemViewModel? postagem = await ObterPostagem(id);

            if(postagem == null) return NotFound();

            if (!UsuarioPodeModificar(postagem)) return Unauthorized();

            if (postagem == null) return NotFound();
            
            return View(postagem);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("editar-postagem/{id:guid}")]
        public async Task<IActionResult> Edit(Guid id, [Bind("Titulo,Conteudo,DataCriacao,IdAutor,Id")] PostagemViewModel postagem)
        {
            if (id != postagem.Id)  return NotFound();

            if (!UsuarioPodeModificar(postagem)) return Unauthorized();

            if (ModelState.IsValid)
            {
                postagem.DataAtualizacao = DateTime.Now;
                await _postagemRepository.Atualizar(_mapper.Map<Postagem>(postagem));

                return RedirectToAction(nameof(Index));
            }

            return View(postagem);
        }


        [HttpGet, ActionName("Delete")]
        [Route("excluir-postagem/{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            PostagemViewModel? postagem = await ObterPostagem(id);

            if (postagem == null) return NotFound();

            if (!UsuarioPodeModificar(postagem)) return Unauthorized();

            return View(postagem); 
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Route("excluir-postagem/{id:guid}")]
        public async Task<IActionResult> DeleteConfirmado(Guid id)
        {
            PostagemViewModel? postagem = await ObterPostagem(id);

            if (postagem == null) return NotFound();

            if (!UsuarioPodeModificar(postagem)) return Unauthorized();

            await _postagemService.Remover(id);

            return RedirectToAction("Index");
        }



        private bool PostagemExists(Guid id)
        {
            return _postagemRepository.ObterPostagem(id) != null;
        }


        private async Task<PostagemViewModel?> ObterPostagem(Guid? id)
        {
            if (id == null)
                return null;

            var postagem = _mapper.Map<PostagemViewModel>(await _postagemRepository.ObterPostagem(Guid.Parse(id.ToString())));
            return postagem;
        }

        private bool UsuarioPodeModificar(PostagemViewModel comentario)
        {
            return UserAdmin || UserId == comentario.IdAutor;
        }

        private async Task CriarAutorSeNaoExistir()
        {
            IEnumerable<Autor> _autor = await _autorRepository.Buscar(p => p.Id == UserId);

            if (_autor == null || !_autor.Any())
            {
                var _insAutor = new Autor
                {
                    Email = UserName,
                    Nome = UserName,
                    Id = UserId,
                    Biografia = ""
                };


                await _autorService.Adicionar(_insAutor);
            }
        }

    }
}

Blog.Net/src/Blog.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Blog.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/blog.css" />
    <link rel="stylesheet" href="~/Blog.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Postagem" asp-action="Index">Blog.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Blog.Web 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    @* @RenderSection("Styles", required: false) *@
</body>
</html>